[tool.poetry]
name = "selfie-lib"
version = "0.1.0"
description = "Infrastructure for creating selfie-compatible test runner plugins."
authors = ["Selina Delgado <sdelgado411@gmail.com>","Harvir Sahota <hsahota2312@gmail.com>","Ned Twigg <ned.twigg@diffplug.com>","Edwin Ye <EdwinYeDeveloper@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.0"
pyright = "^1.1.350"
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D", "S", "ANN", "FA","N", "PYI", "EM", "PLR", "TRY", "FBT", "COM", "RET", "PT", "PTH",
"E501", # line too long
"PLC0414", # import alias does not rename original package
"W291", # trailing whitespace, we need it for testing snapshots
]

[tool.ruff.lint.flake8-self]
ignore-names = ["__create"]