on:
  push:
    branches: [main]
    paths:
      - 'jvm/**'
defaults:
  run:
    working-directory: jvm
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
      - name: Gradle caching
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew :dokkatooGeneratePublicationHtml
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 0a95e814ccf2b6a95d2dc3bea0a4a2b4
          projectName: selfie-kdoc
          directory: jvm/build/dokka/html
